### ISSUE TITLE
compiler errors in BeaconsViewController

### ISSUE THREAD

**Issue by julapy** [NordicSemiconductor/IOS-nRF-Beacons#1]
line 439 - `[self performAction:[self.beacons[j] action]];`
line 448 - `[self performAction:[self.beacons[j] action]];`

xcode 6.3.1
building with ios8.3

fix,

```
Beacons * beacon = self.beacons[j];
[self performAction:beacon.action];
```

**Comment by Kamran-Soomro** [comment]
thanks for your comment. I have fixed issue with type casting and uploaded the code on github.
fix: [self performAction:[(Beacons *)self.beacons[j] action]];
